name: "LAMBADA"
type: "gen"
module: "tasks.lambada.task.LAMBADA"
path: "lambada_last_word_format_gmask/lambada"

sampling_strategy: "BeamSearchStrategy"
num_beams: 16
use_task_mask: true
unidirectional: true